#############################################################################
# Makefile for building: FSpriteDesigner
# Generated by qmake (2.01a) (Qt 4.8.3) on: Wed Feb 27 21:28:00 2013
# Project:  FSpriteDesigner.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile FSpriteDesigner.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Isrc -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib -lQtXml -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/ui/DsSpriteDisplay.cc \
		src/ui/DsResourceDisplay.cc \
		src/ui/DsPropertyDisplay.cc \
		src/ui/DsMainFrame.cc \
		src/ui/DsEditView.cc \
		src/ui/DsEditSpace.cc \
		src/ui/DsEditState.cc \
		src/ui/DsAnmationEdit.cc \
		src/model/DsResourceMgr.cc \
		src/model/DsProject.cc \
		src/model/DsFrame.cc \
		src/model/DsData.cc \
		src/model/DsAnimation.cc \
		src/model/DsFrameImage.cc \
		src/model/DsSprite.cc \
		src/operator/DsDataOperator.cc \
		src/operator/DsOperator.cc \
		src/operator/DsAnimationOperator.cc \
		src/operator/DsIoOperator.cc \
		src/operator/DsAuxOperator.cc \
		src/util/DsUtilLoader.cc \
		src/util/DsUtil.cc \
		src/main.cc moc_DsSpriteDisplay.cpp \
		moc_DsResourceDisplay.cpp \
		moc_DsPropertyDisplay.cpp \
		moc_DsMainFrame.cpp \
		moc_DsEditView.cpp \
		moc_DsEditSpace.cpp \
		moc_DsData.cpp \
		moc_DsAnimationEdit.cpp \
		moc_DsAnimationOperator.cpp \
		qrc_res.cpp
OBJECTS       = DsSpriteDisplay.o \
		DsResourceDisplay.o \
		DsPropertyDisplay.o \
		DsMainFrame.o \
		DsEditView.o \
		DsEditSpace.o \
		DsEditState.o \
		DsAnmationEdit.o \
		DsResourceMgr.o \
		DsProject.o \
		DsFrame.o \
		DsData.o \
		DsAnimation.o \
		DsFrameImage.o \
		DsSprite.o \
		DsDataOperator.o \
		DsOperator.o \
		DsAnimationOperator.o \
		DsIoOperator.o \
		DsAuxOperator.o \
		DsUtilLoader.o \
		DsUtil.o \
		main.o \
		moc_DsSpriteDisplay.o \
		moc_DsResourceDisplay.o \
		moc_DsPropertyDisplay.o \
		moc_DsMainFrame.o \
		moc_DsEditView.o \
		moc_DsEditSpace.o \
		moc_DsData.o \
		moc_DsAnimationEdit.o \
		moc_DsAnimationOperator.o \
		qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		FSpriteDesigner.pro
QMAKE_TARGET  = FSpriteDesigner
DESTDIR       = 
TARGET        = FSpriteDesigner

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_animation_info.h ui_about.h ui_scale.h ui_pisition.h ui_frame.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: FSpriteDesigner.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtXml.prl \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile FSpriteDesigner.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtXml.prl:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile FSpriteDesigner.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/FSpriteDesigner1.0.0 || $(MKDIR) .tmp/FSpriteDesigner1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FSpriteDesigner1.0.0/ && $(COPY_FILE) --parents src/ui/DsSpriteDisplay.h src/ui/DsResourceDisplay.h src/ui/DsQrcMacros.h src/ui/DsPropertyDisplay.h src/ui/DsMainFrame.h src/ui/DsEditView.h src/ui/DsEditSpace.h src/operator/DsDataOperator.h src/model/DsSprite.h src/model/DsResourceMgr.h src/model/DsFrameImage.h src/model/DsFrame.h src/model/DsData.h src/model/DsAnimation.h src/ui/DsEditState.h src/operator/DsOperator.h src/operator/DsDataOperator.h src/ui/DsAnimationEdit.h src/util/DsDebug.h src/operator/DsAnimationOperator.h src/util/DsUtil.h src/operator/DsIoOperator.h src/model/DsProject.h src/util/DsUtilLoader.h src/model/DsModel.h src/operator/DsAuxOperator.h .tmp/FSpriteDesigner1.0.0/ && $(COPY_FILE) --parents resource/images/res.qrc .tmp/FSpriteDesigner1.0.0/ && $(COPY_FILE) --parents src/ui/DsSpriteDisplay.cc src/ui/DsResourceDisplay.cc src/ui/DsPropertyDisplay.cc src/ui/DsMainFrame.cc src/ui/DsEditView.cc src/ui/DsEditSpace.cc src/ui/DsEditState.cc src/ui/DsAnmationEdit.cc src/model/DsResourceMgr.cc src/model/DsProject.cc src/model/DsFrame.cc src/model/DsData.cc src/model/DsAnimation.cc src/model/DsFrameImage.cc src/model/DsSprite.cc src/operator/DsDataOperator.cc src/operator/DsOperator.cc src/operator/DsAnimationOperator.cc src/operator/DsIoOperator.cc src/operator/DsAuxOperator.cc src/util/DsUtilLoader.cc src/util/DsUtil.cc src/main.cc .tmp/FSpriteDesigner1.0.0/ && $(COPY_FILE) --parents resource/ui/animation_info.ui resource/ui/about.ui resource/ui/scale.ui resource/ui/pisition.ui resource/ui/frame.ui .tmp/FSpriteDesigner1.0.0/ && (cd `dirname .tmp/FSpriteDesigner1.0.0` && $(TAR) FSpriteDesigner1.0.0.tar FSpriteDesigner1.0.0 && $(COMPRESS) FSpriteDesigner1.0.0.tar) && $(MOVE) `dirname .tmp/FSpriteDesigner1.0.0`/FSpriteDesigner1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FSpriteDesigner1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_DsSpriteDisplay.cpp moc_DsResourceDisplay.cpp moc_DsPropertyDisplay.cpp moc_DsMainFrame.cpp moc_DsEditView.cpp moc_DsEditSpace.cpp moc_DsData.cpp moc_DsAnimationEdit.cpp moc_DsAnimationOperator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_DsSpriteDisplay.cpp moc_DsResourceDisplay.cpp moc_DsPropertyDisplay.cpp moc_DsMainFrame.cpp moc_DsEditView.cpp moc_DsEditSpace.cpp moc_DsData.cpp moc_DsAnimationEdit.cpp moc_DsAnimationOperator.cpp
moc_DsSpriteDisplay.cpp: src/ui/DsSpriteDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/DsSpriteDisplay.h -o moc_DsSpriteDisplay.cpp

moc_DsResourceDisplay.cpp: src/ui/DsResourceDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/DsResourceDisplay.h -o moc_DsResourceDisplay.cpp

moc_DsPropertyDisplay.cpp: src/ui/DsPropertyDisplay.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/DsPropertyDisplay.h -o moc_DsPropertyDisplay.cpp

moc_DsMainFrame.cpp: src/ui/DsResourceDisplay.h \
		src/ui/DsEditSpace.h \
		src/ui/DsEditView.h \
		src/ui/DsEditState.h \
		src/ui/DsAnimationEdit.h \
		src/ui/DsSpriteDisplay.h \
		src/ui/DsPropertyDisplay.h \
		src/ui/DsMainFrame.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/DsMainFrame.h -o moc_DsMainFrame.cpp

moc_DsEditView.cpp: src/ui/DsEditState.h \
		src/ui/DsEditView.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/DsEditView.h -o moc_DsEditView.cpp

moc_DsEditSpace.cpp: src/ui/DsEditView.h \
		src/ui/DsEditState.h \
		src/ui/DsAnimationEdit.h \
		src/ui/DsEditSpace.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/DsEditSpace.h -o moc_DsEditSpace.cpp

moc_DsData.cpp: src/model/DsProject.h \
		src/model/DsSprite.h \
		src/model/DsFrame.h \
		src/model/DsFrameImage.h \
		src/model/DsAnimation.h \
		src/model/DsData.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/model/DsData.h -o moc_DsData.cpp

moc_DsAnimationEdit.cpp: src/ui/DsAnimationEdit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ui/DsAnimationEdit.h -o moc_DsAnimationEdit.cpp

moc_DsAnimationOperator.cpp: src/operator/DsAnimationOperator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/operator/DsAnimationOperator.h -o moc_DsAnimationOperator.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: resource/images/res.qrc \
		resource/images/IDI_FILE_OPEN.png \
		resource/images/IDI_PLAY.png \
		resource/images/IDI_CUT.png \
		resource/images/IDI_SAVE.png \
		resource/images/IDI_STOP.png \
		resource/images/IDI_MOVE_UP.png \
		resource/images/IDI_EXPORT.png \
		resource/images/IDI_CLOSE.png \
		resource/images/IDI_NEW.png \
		resource/images/IDI_HELP.png \
		resource/images/IDI_ANIMATION.png \
		resource/images/IDI_ZOOM_IN.png \
		resource/images/IDI_FRAMES.png \
		resource/images/IDI_DELETE.png \
		resource/images/IDI_PERSITION.png \
		resource/images/IDI_MOVE_FRONT.png \
		resource/images/IDI_SOFTWARE.ico \
		resource/images/IDI_TEAM_LOGO.png \
		resource/images/IDI_OPEN.png \
		resource/images/IDI_EXIT.png \
		resource/images/IDI_SPRITE.png \
		resource/images/IDI_MOVE_DOWN.png \
		resource/images/IDI_ZOOM_OUT.png \
		resource/images/IDI_FOWARD.png \
		resource/images/IDI_UNDO.png \
		resource/images/FAERIS_LOGO.png \
		resource/images/IDI_COPY.png \
		resource/images/IDI_RESIZE.png \
		resource/images/IDI_ADD.png \
		resource/images/IDI_PROJECT.png \
		resource/images/IDI_ROTATE.png \
		resource/images/IDI_GRID.png \
		resource/images/IDI_ADD_BKGND.png \
		resource/images/IDI_COORDINATE.png \
		resource/images/IDI_SCALE.png \
		resource/images/IDI_PAST.png \
		resource/images/IDI_SAVE_AS.png \
		resource/images/IDI_MOVE_END.png
	/usr/bin/rcc -name res resource/images/res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_animation_info.h ui_about.h ui_scale.h ui_pisition.h ui_frame.h
compiler_uic_clean:
	-$(DEL_FILE) ui_animation_info.h ui_about.h ui_scale.h ui_pisition.h ui_frame.h
ui_animation_info.h: resource/ui/animation_info.ui
	/usr/bin/uic-qt4 resource/ui/animation_info.ui -o ui_animation_info.h

ui_about.h: resource/ui/about.ui
	/usr/bin/uic-qt4 resource/ui/about.ui -o ui_about.h

ui_scale.h: resource/ui/scale.ui
	/usr/bin/uic-qt4 resource/ui/scale.ui -o ui_scale.h

ui_pisition.h: resource/ui/pisition.ui
	/usr/bin/uic-qt4 resource/ui/pisition.ui -o ui_pisition.h

ui_frame.h: resource/ui/frame.ui
	/usr/bin/uic-qt4 resource/ui/frame.ui -o ui_frame.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

DsSpriteDisplay.o: src/ui/DsSpriteDisplay.cc src/ui/DsSpriteDisplay.h \
		src/ui/DsQrcMacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsSpriteDisplay.o src/ui/DsSpriteDisplay.cc

DsResourceDisplay.o: src/ui/DsResourceDisplay.cc src/ui/DsQrcMacros.h \
		src/ui/DsResourceDisplay.h \
		src/model/DsData.h \
		src/model/DsProject.h \
		src/model/DsSprite.h \
		src/model/DsFrame.h \
		src/model/DsFrameImage.h \
		src/model/DsAnimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsResourceDisplay.o src/ui/DsResourceDisplay.cc

DsPropertyDisplay.o: src/ui/DsPropertyDisplay.cc src/ui/DsPropertyDisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsPropertyDisplay.o src/ui/DsPropertyDisplay.cc

DsMainFrame.o: src/ui/DsMainFrame.cc src/ui/DsMainFrame.h \
		src/ui/DsResourceDisplay.h \
		src/ui/DsEditSpace.h \
		src/ui/DsEditView.h \
		src/ui/DsEditState.h \
		src/ui/DsAnimationEdit.h \
		src/ui/DsSpriteDisplay.h \
		src/ui/DsPropertyDisplay.h \
		src/ui/DsQrcMacros.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsMainFrame.o src/ui/DsMainFrame.cc

DsEditView.o: src/ui/DsEditView.cc src/ui/DsEditView.h \
		src/ui/DsEditState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsEditView.o src/ui/DsEditView.cc

DsEditSpace.o: src/ui/DsEditSpace.cc src/ui/DsEditSpace.h \
		src/ui/DsEditView.h \
		src/ui/DsEditState.h \
		src/ui/DsAnimationEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsEditSpace.o src/ui/DsEditSpace.cc

DsEditState.o: src/ui/DsEditState.cc src/ui/DsEditState.h \
		src/ui/DsEditView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsEditState.o src/ui/DsEditState.cc

DsAnmationEdit.o: src/ui/DsAnmationEdit.cc src/ui/DsAnimationEdit.h \
		src/ui/DsEditView.h \
		src/ui/DsEditState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsAnmationEdit.o src/ui/DsAnmationEdit.cc

DsResourceMgr.o: src/model/DsResourceMgr.cc src/model/DsResourceMgr.h \
		src/model/DsData.h \
		src/model/DsProject.h \
		src/model/DsSprite.h \
		src/model/DsFrame.h \
		src/model/DsFrameImage.h \
		src/model/DsAnimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsResourceMgr.o src/model/DsResourceMgr.cc

DsProject.o: src/model/DsProject.cc src/model/DsProject.h \
		src/model/DsSprite.h \
		src/model/DsFrame.h \
		src/model/DsFrameImage.h \
		src/model/DsAnimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsProject.o src/model/DsProject.cc

DsFrame.o: src/model/DsFrame.cc src/model/DsFrame.h \
		src/model/DsFrameImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsFrame.o src/model/DsFrame.cc

DsData.o: src/model/DsData.cc src/model/DsData.h \
		src/model/DsProject.h \
		src/model/DsSprite.h \
		src/model/DsFrame.h \
		src/model/DsFrameImage.h \
		src/model/DsAnimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsData.o src/model/DsData.cc

DsAnimation.o: src/model/DsAnimation.cc src/model/DsAnimation.h \
		src/model/DsFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsAnimation.o src/model/DsAnimation.cc

DsFrameImage.o: src/model/DsFrameImage.cc src/model/DsFrameImage.h \
		src/model/DsResourceMgr.h \
		src/model/DsData.h \
		src/model/DsProject.h \
		src/model/DsSprite.h \
		src/model/DsFrame.h \
		src/model/DsAnimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsFrameImage.o src/model/DsFrameImage.cc

DsSprite.o: src/model/DsSprite.cc src/model/DsSprite.h \
		src/model/DsFrame.h \
		src/model/DsFrameImage.h \
		src/model/DsAnimation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsSprite.o src/model/DsSprite.cc

DsDataOperator.o: src/operator/DsDataOperator.cc src/operator/DsDataOperator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsDataOperator.o src/operator/DsDataOperator.cc

DsOperator.o: src/operator/DsOperator.cc src/operator/DsOperator.h \
		src/operator/DsDataOperator.h \
		src/operator/DsAnimationOperator.h \
		src/operator/DsIoOperator.h \
		src/operator/DsAuxOperator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsOperator.o src/operator/DsOperator.cc

DsAnimationOperator.o: src/operator/DsAnimationOperator.cc src/operator/DsAnimationOperator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsAnimationOperator.o src/operator/DsAnimationOperator.cc

DsIoOperator.o: src/operator/DsIoOperator.cc src/operator/DsIoOperator.h \
		src/operator/DsOperator.h \
		src/operator/DsDataOperator.h \
		src/operator/DsAnimationOperator.h \
		src/operator/DsAuxOperator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsIoOperator.o src/operator/DsIoOperator.cc

DsAuxOperator.o: src/operator/DsAuxOperator.cc src/operator/DsAuxOperator.h \
		src/operator/DsOperator.h \
		src/operator/DsDataOperator.h \
		src/operator/DsAnimationOperator.h \
		src/operator/DsIoOperator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsAuxOperator.o src/operator/DsAuxOperator.cc

DsUtilLoader.o: src/util/DsUtilLoader.cc src/util/DsUtilLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsUtilLoader.o src/util/DsUtilLoader.cc

DsUtil.o: src/util/DsUtil.cc src/util/DsUtil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DsUtil.o src/util/DsUtil.cc

main.o: src/main.cc src/ui/DsMainFrame.h \
		src/ui/DsResourceDisplay.h \
		src/ui/DsEditSpace.h \
		src/ui/DsEditView.h \
		src/ui/DsEditState.h \
		src/ui/DsAnimationEdit.h \
		src/ui/DsSpriteDisplay.h \
		src/ui/DsPropertyDisplay.h \
		src/ui/DsQrcMacros.h \
		src/model/DsModel.h \
		src/model/DsAnimation.h \
		src/model/DsData.h \
		src/model/DsProject.h \
		src/model/DsSprite.h \
		src/model/DsFrame.h \
		src/model/DsFrameImage.h \
		src/model/DsResourceMgr.h \
		src/operator/DsOperator.h \
		src/operator/DsDataOperator.h \
		src/operator/DsAnimationOperator.h \
		src/operator/DsIoOperator.h \
		src/operator/DsAuxOperator.h \
		src/util/DsSpriteUtil.h \
		src/util/DsDebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cc

moc_DsSpriteDisplay.o: moc_DsSpriteDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsSpriteDisplay.o moc_DsSpriteDisplay.cpp

moc_DsResourceDisplay.o: moc_DsResourceDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsResourceDisplay.o moc_DsResourceDisplay.cpp

moc_DsPropertyDisplay.o: moc_DsPropertyDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsPropertyDisplay.o moc_DsPropertyDisplay.cpp

moc_DsMainFrame.o: moc_DsMainFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsMainFrame.o moc_DsMainFrame.cpp

moc_DsEditView.o: moc_DsEditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsEditView.o moc_DsEditView.cpp

moc_DsEditSpace.o: moc_DsEditSpace.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsEditSpace.o moc_DsEditSpace.cpp

moc_DsData.o: moc_DsData.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsData.o moc_DsData.cpp

moc_DsAnimationEdit.o: moc_DsAnimationEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsAnimationEdit.o moc_DsAnimationEdit.cpp

moc_DsAnimationOperator.o: moc_DsAnimationOperator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DsAnimationOperator.o moc_DsAnimationOperator.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

